config/routes.rb
Rails.application.routes.draw do
  root to: 'skills_users#home'
  resources :skills_users
  resources :skills
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :parent_skill, class_name: 'Skill', 
              foreign_key: 'parent_skill_id', 
              optional: true
  has_many :children_skill, class_name: 'Skill', 
            foreign_key: 'parent_skill_id', dependent: :nullify
  has_many :skills_users, dependent: :destroy
  has_many :users, through: :skills_users
  validates :name, presence: true
  validates :name, uniqueness: true
  validate :is_parent?
  validate :parent_is_parent?, :if => :data_valid?
  scope :get_parents, -> {where(parent_skill_id: nil)}

  def number_of_users
  	users.length
  end

  def number_of_points
  	users.sum(&:points)
  end
  def data_valid?
    parent_skill_id? && name?
  end
  def is_parent?
  	errors.add(:base, 'The skill is already a parent skill') if children_skill.any?
  end
  def parent_is_parent?
    if parent_skill.present?
      errors.add(:base, 'The parent skill is already a child') if parent_skill.parent_skill_id?
    end
  end

end

app/models/skills_user.rb
class SkillsUser < ApplicationRecord
  belongs_to :skill
  belongs_to :user
  validates :skill_id, presence: true, numericality: { only_integer: true }
  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :user, uniqueness: {scope: :skill}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :skills_users, dependent: :destroy
	has_many :skills, through: :skills_users, dependent: :nullify
	validates :points, presence: true
	validates :points, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)
    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :parent_skill_id)
    end
end

app/controllers/skills_users_controller.rb
require 'skills_helper'

class SkillsUsersController < ApplicationController
  before_action :set_skills_user, only: [:show, :edit, :update, :destroy]

  # GET /skills_users
  # GET /skills_users.json
  def index
    @skills_users = SkillsUser.all
  end

  # GET /skills_users/1
  # GET /skills_users/1.json
  def show
  end

  # GET /skills_users/new
  def new
    @skills_user = SkillsUser.new
  end

  # GET /skills_users/1/edit
  def edit
  end

  # POST /skills_users
  # POST /skills_users.json
  def create
    @skills_user = SkillsUser.new(skills_user_params)
    
    respond_to do |format|
      if @skills_user.save
        format.html { redirect_to @skills_user, notice: 'Skills was successfully associated to user.' }
        format.json { render :show, status: :created, location: @skills_user }
      else
        #puts "Raise error #{@skills_user.errors.full_messages}"
        format.html { render :new }
        format.json { render json: @skills_user.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /skills_users/1
  # PATCH/PUT /skills_users/1.json
  def update
    @skills = Skill.all
    @users = User.all
    
    respond_to do |format|
      if @skills_user.update(skills_user_params)
        format.html { redirect_to @skills_user, notice: 'Skills user was successfully updated.' }
        format.json { render :show, status: :ok, location: @skills_user }
      else
        puts "Raise error #{@skills_user.errors.full_messages}"
        format.html { render :edit }
        format.json { render json: @skills_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills_users/1
  # DELETE /skills_users/1.json
  def destroy
    @skills_user.destroy
    respond_to do |format|
      format.html { redirect_to skills_users_url, notice: 'Skills user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def home
    @skills_points = SkillsHelper.consolidate
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skills_user
      @skills_user = SkillsUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skills_user_params
      params.require(:skills_user).permit(:skill_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:points)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skills_users_helper.rb
module SkillsUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgorizeTestRonr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div>
      <br>
    <%= button_to 'Home', root_path, :class => 'btn btn-secondary btn-lg active', method: :get %>
    </div>
  </body>
</html>

app/views/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control form-control-sm" %>
    </div>
    <div class="col-md-2">
      <%= form.label :parent_skill_id %>
      <%= form.select(:parent_skill_id, options_for_select(Skill.all.map{|skill| [skill.name, skill.id]}), {:include_blank => 'None Specified'},{ :class => "form-control form-control-sm" })%>
    </div>
  </div>

  <div style="margin-top: 15px">
    <div class="actions">
      <%= form.submit nil, :class => "btn btn-secondary btn-sm active"   %>
    </div>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<div class="col-md-16">
	<ul class="nav">
		<div style="margin-right: 2px">
		   <li class="nav-item">
    			<%= link_to 'Show', @skill,  :class => "btn btn-secondary btn-sm active"  %>
   			</li>
   			</div>
		<div style="margin-right: 2px">
		   <li class="nav-item"> 
		    <%= link_to 'Back', skills_path,  :class => "btn btn-secondary btn-sm active"  %>
		   </li>
		</div>
	</ul>
</div>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent skill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.parent_skill_id %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<ul class="nav">
   <li class="nav-item"> 
    <%= link_to 'New Skill', new_skill_path,  :class => "btn btn-secondary btn-sm active"  %>
   </li>
</ul>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<ul class="nav">
   <li class="nav-item"> 
    <%= link_to 'Show table Skills', skills_path,  :class => "btn btn-secondary btn-sm active"  %>
   </li>
</ul>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Parent skill:</strong>
  <% if @skill.parent_skill != nil %> 
    <%= @skill.parent_skill.id %>
  <% end %>
</p>

<div class="col-md-16">
  <ul class="nav">
    <div style="margin-right: 2px">
     <li class="nav-item"> 
      <%= link_to 'Edit', edit_skill_path(@skill),  :class => "btn btn-secondary btn-sm active"  %>
     </li>
    </div>
    <div style="margin-right: 2px">
     <li class="nav-item"> 
      <%= link_to 'Back', skills_path,  :class => "btn btn-secondary btn-sm active"  %>
     </li>
   </div>
  </ul>
</div>

app/views/skills_users/_form.html.erb
<%= form_with(model: skills_user, local: true) do |form| %>
  <% if skills_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skills_user.errors.count, "error") %> prohibited this skills_user from being saved:</h2>

      <ul>
      <% skills_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :skill_id %>
      <%= form.select(:skill_id, options_for_select(Skill.all.map{|skill| [skill.name, skill.id]}),{},{ :class => "form-control form-control-sm" })%>
    </div>
    <div class="col-md-2">
      <%= form.label :user_id %>
      <%= form.select(:user_id, options_for_select(User.all.map{|user| ["ID #{user.id} : #{user.points} points", user.id]}),{},{ :class => "form-control form-control-sm" })%>
    </div>
  </div>

<div style="margin-top: 15px; margin-bottom: 15px">
  <%= form.submit nil, :class => "btn btn-secondary btn-sm active"  %>
</div>

<% end %>

app/views/skills_users/edit.html.erb
<h1>Editing Skills User</h1>

<%= render 'form', skills_user: @skills_user %>

<div class="col-md-16">
	<ul class="nav">
		<div style="margin-right: 2px">
		   <li class="nav-item"> 
		    <%= link_to 'Show', @skills_user,  :class => "btn btn-secondary btn-sm active"  %>
		   </li>
		</div>
		<div style="margin-right: 2px">
		   <li class="nav-item"> 
		    <%= link_to 'Back', skills_users_path,  :class => "btn btn-secondary btn-sm active"  %>
		   </li>
		</div>
</ul>

app/views/skills_users/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome!</h1>
<h1>Agorize Test RubyOnRails</h1>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Skill</th>
      <th scope="col">Points</th>
      <th scope="col">Number of users</th>
    </tr>
  </thead>
  <tbody>
    <% @skills_points.each do |skills_point| %>
      <tr>
        <td><%= skills_point[:name] %></td>
        <td><%= skills_point[:number_of_points] %></td>
        <td><%= skills_point[:number_of_users] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row-md-16">
    <ul class="nav">
      <div style="margin-right: 2px">
        <li class="nav-item">
        <%= link_to 'Create and Manage Users', new_user_path(@user),  :class => "btn btn-secondary btn-sm active"   %>
        </li>
      </div>
      <div style="margin-right: 2px">
        <li class="nav-item">
        <%= link_to 'Create and Manage Skills', new_skill_path(@skill),  :class => "btn btn-secondary btn-sm active"   %>
        </li>
      </div>
      <div style="margin-right: 2px">
        <li class="nav-item">
        <%= link_to 'Associate Skills to Users', new_skills_user_path(@skills_user),  :class => "btn btn-secondary btn-sm active"   %>
        </li>
      </div>
    </div>
  </ul>
  </div>
</div>

app/views/skills_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills and Users</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Skill</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills_users.each do |skills_user| %>
      <tr>
        <td><%= skills_user.skill.name %></td>
        <td><%= skills_user.user.id %></td>
        <td><%= link_to 'Show', skills_user %></td>
        <td><%= link_to 'Edit', edit_skills_user_path(skills_user) %></td>
        <td><%= link_to 'Destroy', skills_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<ul class="nav">
   <li class="nav-item"> 
    <%= link_to 'New Skills User', new_skills_user_path,  :class => "btn btn-secondary btn-sm active"  %>
   </li>
</ul>

app/views/skills_users/new.html.erb
<h1>New Skill-User Association</h1>


<%= render 'form', skills_user: @skills_user %>

<ul class="nav">
   <li class="nav-item"> 
    <%= link_to 'Show table Skils and Users', skills_users_path,  :class => "btn btn-secondary btn-sm active" %>
   </li>
</ul>

app/views/skills_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skill:</strong>
  <%= @skills_user.skill.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @skills_user.user.id %>
</p>

<div class="col-md-16">
  <ul class="nav">
    <div style="margin-right: 2px">
        <li class="nav-item">  
          <%= link_to 'Edit', edit_skills_user_path(@skills_user),  :class => "btn btn-secondary btn-sm active"  %>
       </li>
     </div>
     <div style="margin-right: 2px">
       <li class="nav-item"> 
          <%= link_to 'Back', skills_users_path,  :class => "btn btn-secondary btn-sm active"  %>
       </li>
   </div>
  </ul>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-2">
    <%= form.label :points %>
    <%= form.number_field :points, class: "form-control form-control-sm" %>
  </div>
</div>
  <div style="margin-top: 15px">
    <div class="actions">
      <%= form.submit nil, :class => "btn btn-secondary btn-sm active"  %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>


<div class="col-md-16">
	<ul class="nav">
		<div style="margin-right: 2px">
		   <li class="nav-item"> 
		   	 	<%= link_to 'Show', @user,  :class => "btn btn-secondary btn-sm active"  %>
		   </li>
		</div>
		<div style="margin-right: 2px">
		   	<li class="nav-item"> 
		    	<%= link_to 'Back', users_path, :class => "btn btn-secondary btn-sm active" %>
		   </li>
		</div>
</ul>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.points %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<ul class="nav">
   <li class="nav-item"> 
    <%= link_to 'New User', new_user_path,  :class => "btn btn-secondary btn-sm active"  %>
   </li>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<ul class="nav">
	 <li class="nav-item"> 
		<%= link_to 'Show table Users', users_path, :class => "btn btn-secondary btn-sm active"  %>
	 </li>
</ul>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.id %>
</p>
<p>
  <strong>Points:</strong>
  <%= @user.points %>
</p>

<div class="col-md-16">
<ul class="nav">
	<div style="margin-right: 2px">
		<li class="nav-item"> 
			<%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-secondary btn-sm active"  %>
		</li>
	</div>
	<div style="margin-right: 2px">
	 <li class="nav-item"> 
	 	<%= link_to 'Back', users_path, :class => "btn btn-secondary btn-sm active"  %>
	 </li>
	</div>
</ul>